insert into public.products (id, name, slug, description, short_description, headline, subheadline, price, compare_at_price, cost_price, category, images, benefits, details, faqs, status, supplier_name, supplier_url, shipping_estimate)
values
('11111111-1111-4111-8111-111111111111','PawTrim LED Grinder','pawtrim-led-grinder','A compact electric pet nail grinder with LED visibility for calmer at-home grooming routines.','Gentle LED pet nail grinder for easier grooming.','Trim Your Pet''s Nails Safely at Home','A gentle LED nail grinder designed to make grooming easier, safer and less stressful for pets and owners.',29.95,49.95,9.50,'Pet Care','["/placeholders/pawtrim-led-grinder.svg"]','["Gentle grinding for safer trimming","Built-in LED light for better visibility","Easier grooming at home","Designed for dogs and cats","Compact and simple to use"]','{"Product type":"Electric Pet LED Nail Grinder","Bundle suggestion":"2 units for 49.95","Main ad angle":"Stop struggling with nail clippers."}','[{"question":"Is this for dogs and cats?","answer":"Yes. Use slow, gentle passes and follow your pet comfort level."}]','active','Manual supplier TBD','','Estimated 7-14 business days'),
('22222222-2222-4222-8222-222222222222','FreshSeal Compact Vacuum Sealer','freshseal-compact-vacuum-sealer','Compact food vacuum sealer for meal prep and storage.','Compact sealer for fresher food storage.','Keep Food Fresh Longer and Reduce Waste','Simple vacuum sealing for organized kitchens and smarter storage.',34.95,59.95,14.00,'Home & Organization','["/placeholders/freshseal-compact-vacuum-sealer.svg"]','["Helps reduce food waste","Compact countertop footprint","Useful for meal prep","Simple one-touch operation"]','{"Product type":"Compact Food Vacuum Sealer"}','[]','active','Manual supplier TBD','','Estimated 7-14 business days'),
('33333333-3333-4333-8333-333333333333','PowerScrub Drill Brush Kit','powerscrub-drill-brush-kit','Drill brush attachment kit for faster durable-surface cleaning.','Turn your drill into a faster cleaning tool.','Clean Tough Stains Faster With Your Drill','Scrub durable surfaces with less effort using brush attachments made for common household jobs.',24.95,39.95,8.00,'Home & Organization','["/placeholders/powerscrub-drill-brush-kit.svg"]','["Speeds up tough scrubbing","Works with many standard drills","Multiple brush shapes","Great for deep cleaning days"]','{"Product type":"Drill Brush Power Scrubber"}','[]','active','Manual supplier TBD','','Estimated 7-14 business days'),
('44444444-4444-4444-8444-444444444444','ClearFlow Silicone Drain Protector','clearflow-silicone-drain-protector','Flexible silicone drain protector that catches hair and debris.','Catch hair before it clogs the drain.','Stop Hair From Clogging Your Drain','A simple bathroom essential that helps keep drains cleaner with less fuss.',14.95,24.95,3.50,'Home & Organization','["/placeholders/clearflow-silicone-drain-protector.svg"]','["Flexible silicone design","Easy to clean","Fits many common drains","Simple everyday prevention"]','{"Product type":"Silicone Drain Protector"}','[]','active','Manual supplier TBD','','Estimated 7-14 business days'),
('55555555-5555-4555-8555-555555555555','SpaceStep Shoe Organizer','spacestep-shoe-organizer','Stackable shoe organizers for closet shelves.','Double up shoe storage without remodeling.','Double Your Closet Space Instantly','Keep pairs together and make crowded shelves easier to manage.',19.95,34.95,6.00,'Home & Organization','["/placeholders/spacestep-shoe-organizer.svg"]','["Saves shelf space","Keeps shoes paired","Adjustable stacked layout","Useful for apartments and closets"]','{"Product type":"Shoe Storage Organizer"}','[]','active','Manual supplier TBD','','Estimated 7-14 business days'),
('66666666-6666-4666-8666-666666666666','ShadeSnap Magnetic Car Curtain','shadesnap-magnetic-car-curtain','Magnetic car window curtain for shade and privacy.','Quick shade and privacy for car windows.','Instant Shade and Privacy for Your Car','Attach, adjust and remove in seconds for a more comfortable ride.',22.95,39.95,7.00,'Car Essentials','["/placeholders/shadesnap-magnetic-car-curtain.svg"]','["Magnetic attachment","Helps reduce glare","Easy to remove","Compact for travel"]','{"Product type":"Magnetic Car Window Curtain"}','[]','active','Manual supplier TBD','','Estimated 7-14 business days'),
('77777777-7777-4777-8777-777777777777','GripGo Car Phone Holder','gripgo-car-phone-holder','Secure phone mount for navigation visibility.','Keep your phone stable and easy to see.','Keep Your Phone Secure and Visible While Driving','A practical mount for cleaner navigation and hands-free convenience.',18.95,29.95,5.00,'Car Essentials','["/placeholders/gripgo-car-phone-holder.svg"]','["Stable grip","Works for daily navigation","Compact setup","Easy angle adjustment"]','{"Product type":"Phone Mount / Car Phone Holder"}','[]','active','Manual supplier TBD','','Estimated 7-14 business days'),
('88888888-8888-4888-8888-888888888888','LiftDesk Laptop Stand','liftdesk-laptop-stand','Portable laptop stand for cleaner desk setups.','Lift your laptop for a cleaner desk setup.','Improve Your Desk Setup and Posture in Seconds','A simple stand for remote work, study spaces and everyday laptop use.',27.95,44.95,10.00,'Tech Accessories','["/placeholders/liftdesk-laptop-stand.svg"]','["Raises screen height","Portable design","Helps organize desk space","Useful for work and study"]','{"Product type":"Laptop Stand"}','[]','active','Manual supplier TBD','','Estimated 7-14 business days')
on conflict (slug) do nothing;
